import React, { useState } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity,
  Alert, StatusBar, ScrollView, ActivityIndicator
} from 'react-native';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { db } from '../../config/firebase';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { COLORS, COMPANY, SHADOWS } from '../../config/theme';
import { Ionicons } from '@expo/vector-icons';

export default function ReportsScreen({ userData }) {
  const [loading, setLoading] = useState(false);
  const [reportType, setReportType] = useState('sales');
  const [generatedReport, setGeneratedReport] = useState(null);

  const reportTypes = [
    { key: 'sales', label: 'Sales Report', icon: 'receipt-outline', desc: 'All invoices with GST breakup for every shop' },
    { key: 'inventory', label: 'Inventory Report', icon: 'layers-outline', desc: 'Current stock levels and low stock alerts' },
    { key: 'summary', label: 'Summary Report', icon: 'bar-chart-outline', desc: 'Quick overview of sales and inventory per shop' },
    { key: 'returns', label: 'Returns Report', icon: 'refresh-circle-outline', desc: 'All return requests with status' },
  ];

  const generateReport = async () => {
    setLoading(true);
    try {
      const usersSnap = await getDocs(query(collection(db, 'users'), where('role', '==', 'shopkeeper')));
      const shops = usersSnap.docs.map(d => d.data());
      const timestamp = new Date().toLocaleDateString('en-IN').replace(/\//g, '-');
      const now = new Date();
      let csvContent = '';

      const header = `${COMPANY.name} - ${reportType.toUpperCase()} REPORT\n` +
        `GSTIN: ${COMPANY.gstin}\n` +
        `Generated: ${now.toLocaleString('en-IN')}\n` +
        `Generated By: ${userData?.name || userData?.email}\n\n`;

      if (reportType === 'sales') {
        csvContent = 'Shop ID,Shop Name,City,Invoice No,Date,Items,Subtotal,CGST,SGST,Total,Customer Phone\n';
        for (const shop of shops) {
          const snap = await getDocs(query(collection(db, 'sales'), where('shopId', '==', shop.shopId)));
          snap.forEach(d => {
            const s = d.data();
            const date = s.createdAt?.toDate ? s.createdAt.toDate().toLocaleDateString('en-IN') : '';
            const items = (s.items || []).map(i => `${i.productName}(x${i.quantity})`).join('; ');
            csvContent += `"${shop.shopId}","${shop.shopName}","${shop.city || 'Hyderabad'}","${s.invoiceNumber}","${date}","${items}",${(s.subtotal || 0).toFixed(2)},${(s.cgst || 0).toFixed(2)},${(s.sgst || 0).toFixed(2)},${(s.totalAmount || 0).toFixed(2)},"${s.customerPhone || ''}"\n`;
          });
        }
      } else if (reportType === 'inventory') {
        csvContent = 'Shop ID,Shop Name,Product Name,Category,Barcode,HSN,Price,Quantity,Min Stock,Status\n';
        for (const shop of shops) {
          const snap = await getDocs(query(collection(db, 'inventory'), where('shopId', '==', shop.shopId)));
          snap.forEach(d => {
            const i = d.data();
            const status = i.quantity <= 0 ? 'Out of Stock' : i.quantity <= (i.minStock || 5) ? 'Low Stock' : 'In Stock';
            csvContent += `"${shop.shopId}","${shop.shopName}","${i.productName}","${i.category || ''}","${i.barcode || ''}","${i.hsnCode || '6006'}",${i.price || 0},${i.quantity || 0},${i.minStock || 5},"${status}"\n`;
          });
        }
      } else if (reportType === 'summary') {
        csvContent = 'Shop ID,Shop Name,City,Total Sales,Today Sales,Total Orders,Products,Low Stock,Out of Stock\n';
        for (const shop of shops) {
          const salesSnap = await getDocs(query(collection(db, 'sales'), where('shopId', '==', shop.shopId)));
          const invSnap = await getDocs(query(collection(db, 'inventory'), where('shopId', '==', shop.shopId)));
          const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
          let totalSales = 0, todaySales = 0, orders = 0;
          salesSnap.forEach(d => {
            const s = d.data();
            const date = s.createdAt?.toDate ? s.createdAt.toDate() : new Date();
            totalSales += s.totalAmount || 0;
            orders++;
            if (date >= todayStart) todaySales += s.totalAmount || 0;
          });
          const inv = invSnap.docs.map(d => d.data());
          const low = inv.filter(i => i.quantity > 0 && i.quantity <= (i.minStock || 5)).length;
          const out = inv.filter(i => i.quantity <= 0).length;
          csvContent += `"${shop.shopId}","${shop.shopName}","${shop.city || 'Hyderabad'}",${totalSales.toFixed(2)},${todaySales.toFixed(2)},${orders},${inv.length},${low},${out}\n`;
        }
      } else if (reportType === 'returns') {
        csvContent = 'Shop ID,Shop Name,Invoice No,Items,Reason,Refund Amount,Status,Date\n';
        for (const shop of shops) {
          const snap = await getDocs(query(collection(db, 'returns'), where('shopId', '==', shop.shopId)));
          snap.forEach(d => {
            const r = d.data();
            const date = r.createdAt?.toDate ? r.createdAt.toDate().toLocaleDateString('en-IN') : '';
            const items = (r.items || []).map(i => `${i.productName}(x${i.quantity})`).join('; ');
            csvContent += `"${shop.shopId}","${shop.shopName}","${r.invoiceNumber}","${items}","${r.reason}",${(r.totalRefund || 0).toFixed(2)},"${r.status}","${date}"\n`;
          });
        }
      }

      const fileName = `Alankara_${reportType}_${timestamp}.csv`;
      const fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, header + csvContent, { encoding: FileSystem.EncodingType.UTF8 });
      setGeneratedReport({ uri: fileUri, name: fileName });
      Alert.alert('Report Ready', `${fileName} has been generated.`);
    } catch (e) {
      Alert.alert('Error', 'Failed to generate report: ' + e.message);
    }
    setLoading(false);
  };

  const shareReport = async () => {
    if (!generatedReport) return;
    try {
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(generatedReport.uri, {
          mimeType: 'text/csv',
          dialogTitle: 'Share Report',
          UTI: 'public.comma-separated-values-text'
        });
      }
    } catch (e) { Alert.alert('Error', 'Failed to share.'); }
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor={COLORS.primaryDark} />

      <View style={styles.header}>
        <Text style={styles.headerTitle}>Reports</Text>
        <Text style={styles.headerSub}>Generate and export data</Text>
      </View>

      <ScrollView style={styles.scroll} showsVerticalScrollIndicator={false}>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Select Report Type</Text>
          {reportTypes.map(type => (
            <TouchableOpacity
              key={type.key}
              style={[styles.reportCard, reportType === type.key && styles.reportCardActive]}
              onPress={() => { setReportType(type.key); setGeneratedReport(null); }}
            >
              <View style={[styles.reportIcon, reportType === type.key && { backgroundColor: COLORS.primary }]}>
                <Ionicons name={type.icon} size={20} color={reportType === type.key ? COLORS.white : COLORS.textSecondary} />
              </View>
              <View style={styles.reportInfo}>
                <Text style={[styles.reportLabel, reportType === type.key && { color: COLORS.primary }]}>{type.label}</Text>
                <Text style={styles.reportDesc}>{type.desc}</Text>
              </View>
              {reportType === type.key && <Ionicons name="checkmark-circle" size={20} color={COLORS.primary} />}
            </TouchableOpacity>
          ))}
        </View>

        <View style={styles.section}>
          <TouchableOpacity
            style={[styles.generateBtn, loading && { opacity: 0.6 }]}
            onPress={generateReport} disabled={loading}
          >
            {loading ? (
              <ActivityIndicator color={COLORS.white} />
            ) : (
              <>
                <Ionicons name="download-outline" size={20} color={COLORS.white} />
                <Text style={styles.generateBtnText}>Generate Report</Text>
              </>
            )}
          </TouchableOpacity>

          {generatedReport && (
            <View style={styles.readyCard}>
              <Ionicons name="checkmark-circle" size={28} color={COLORS.success} />
              <View style={styles.readyInfo}>
                <Text style={styles.readyTitle}>Report Ready</Text>
                <Text style={styles.readyName}>{generatedReport.name}</Text>
              </View>
              <TouchableOpacity style={styles.shareBtn} onPress={shareReport}>
                <Ionicons name="share-outline" size={20} color={COLORS.white} />
              </TouchableOpacity>
            </View>
          )}
        </View>

        <View style={styles.section}>
          <View style={styles.infoCard}>
            <Text style={styles.infoTitle}>How to open in Excel</Text>
            <Text style={styles.infoStep}>1. Tap "Generate Report" button above</Text>
            <Text style={styles.infoStep}>2. Tap the share button when report is ready</Text>
            <Text style={styles.infoStep}>3. Choose "Save to Files" or "Open in Excel"</Text>
            <Text style={styles.infoStep}>4. All shop data is organized with Shop ID labels</Text>
          </View>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: { backgroundColor: COLORS.primary, paddingHorizontal: 16, paddingTop: 50, paddingBottom: 16 },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.white },
  headerSub: { fontSize: 12, color: 'rgba(255,255,255,0.7)', marginTop: 2 },
  scroll: { flex: 1 },
  section: { paddingHorizontal: 16, marginTop: 20 },
  sectionTitle: { fontSize: 13, fontWeight: '700', color: COLORS.textSecondary, marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.5 },
  reportCard: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    backgroundColor: COLORS.white, borderRadius: 12, padding: 14,
    marginBottom: 10, borderWidth: 1, borderColor: COLORS.border, ...SHADOWS.small
  },
  reportCardActive: { borderColor: COLORS.primary, backgroundColor: '#FDF9F9' },
  reportIcon: { width: 40, height: 40, borderRadius: 10, backgroundColor: COLORS.background, justifyContent: 'center', alignItems: 'center' },
  reportInfo: { flex: 1 },
  reportLabel: { fontSize: 14, fontWeight: '600', color: COLORS.text },
  reportDesc: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },
  generateBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: COLORS.primary, borderRadius: 12, padding: 16, gap: 10, ...SHADOWS.medium
  },
  generateBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 15 },
  readyCard: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    backgroundColor: COLORS.successLight, borderRadius: 12, padding: 14, marginTop: 12
  },
  readyInfo: { flex: 1 },
  readyTitle: { fontSize: 14, fontWeight: '600', color: COLORS.success },
  readyName: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },
  shareBtn: { backgroundColor: COLORS.success, padding: 10, borderRadius: 8 },
  infoCard: { backgroundColor: COLORS.white, borderRadius: 12, padding: 16, borderLeftWidth: 4, borderLeftColor: COLORS.primary },
  infoTitle: { fontSize: 13, fontWeight: '700', color: COLORS.primary, marginBottom: 10 },
  infoStep: { fontSize: 13, color: COLORS.textSecondary, marginBottom: 6 }
});
